export const GET_FEDERAL_OFFICES = "GET_FEDERAL_OFFICES";
export const GET_STATE_OFFICES = "GET_STATE_OFFICES";
export const GET_FEDERAL_CANDIDATES = "GET_FEDERAL_CANDIDATES";
export const GET_FEDERAL_CANDIDATES_PARTICULAR =
  "GET_FEDERAL_CANDIDATE_PARTICULAR";
export const GET_TOP_CANDIDATES = "GET_TOP_CANDIDATES";
export const GET_STATE_CANDIDATES = "GET_STATE_CANDIDATES";
export const GET_TOP_STATE_CANDIDATES = "GET_TOP_STATE_CANDIDATES";
