# Generated by Django 3.0.7 on 2020-07-02 00:55

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StateElection',
            fields=[
                ('election_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='cheatsheet2020.Election')),
                ('state', localflavor.us.models.USStateField(max_length=2, primary_key=True, serialize=False)),
                ('num_districts_in_state', models.IntegerField()),
                ('num_counties_in_state', models.IntegerField()),
            ],
            bases=('cheatsheet2020.election',),
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheatsheet2020.Election')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheatsheet2020.Office')),
            ],
        ),
        migrations.CreateModel(
            name='DistrictElection',
            fields=[
                ('election_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='cheatsheet2020.Election')),
                ('district', models.IntegerField(primary_key=True, serialize=False)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheatsheet2020.StateElection')),
            ],
            bases=('cheatsheet2020.election',),
        ),
        migrations.CreateModel(
            name='CountyElection',
            fields=[
                ('election_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='cheatsheet2020.Election')),
                ('county', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheatsheet2020.StateElection')),
            ],
            bases=('cheatsheet2020.election',),
        ),
    ]
