# Generated by Django 3.0.7 on 2020-07-08 00:58

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('score', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('exe', 'Executive'), ('leg', 'Legislative'), ('jud', 'Judicial'), ('oth', 'Other')], default='exe', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='FederalElection',
            fields=[
                ('election_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cheatsheet2020.Election')),
            ],
            bases=('cheatsheet2020.election',),
        ),
        migrations.CreateModel(
            name='LocalElection',
            fields=[
                ('election_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='cheatsheet2020.Election')),
                ('local_area', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            bases=('cheatsheet2020.election',),
        ),
        migrations.CreateModel(
            name='StateElection',
            fields=[
                ('election_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='cheatsheet2020.Election')),
                ('state', localflavor.us.models.USStateField(max_length=2, primary_key=True, serialize=False)),
                ('num_districts_in_state', models.IntegerField()),
                ('num_counties_in_state', models.IntegerField()),
                ('federal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheatsheet2020.FederalElection')),
            ],
            bases=('cheatsheet2020.election',),
        ),
        migrations.CreateModel(
            name='StateOffice',
            fields=[
                ('office_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cheatsheet2020.Office')),
                ('name', models.CharField(max_length=200)),
                ('state_election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheatsheet2020.StateElection')),
            ],
            options={
                'unique_together': {('state_election', 'name')},
            },
            bases=('cheatsheet2020.office',),
        ),
        migrations.CreateModel(
            name='StateCandidate',
            fields=[
                ('candidate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cheatsheet2020.Candidate')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheatsheet2020.StateOffice')),
            ],
            bases=('cheatsheet2020.candidate',),
        ),
        migrations.CreateModel(
            name='LocalOffice',
            fields=[
                ('office_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cheatsheet2020.Office')),
                ('name', models.CharField(max_length=200)),
                ('local_election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheatsheet2020.LocalElection')),
            ],
            options={
                'unique_together': {('local_election', 'name')},
            },
            bases=('cheatsheet2020.office',),
        ),
        migrations.AddField(
            model_name='localelection',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheatsheet2020.StateElection'),
        ),
        migrations.CreateModel(
            name='LocalCandidate',
            fields=[
                ('candidate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cheatsheet2020.Candidate')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheatsheet2020.LocalOffice')),
            ],
            bases=('cheatsheet2020.candidate',),
        ),
        migrations.CreateModel(
            name='FederalOffice',
            fields=[
                ('office_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cheatsheet2020.Office')),
                ('name', models.CharField(max_length=200)),
                ('federal_election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheatsheet2020.FederalElection')),
            ],
            options={
                'unique_together': {('federal_election', 'name')},
            },
            bases=('cheatsheet2020.office',),
        ),
        migrations.CreateModel(
            name='FederalCandidate',
            fields=[
                ('candidate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cheatsheet2020.Candidate')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheatsheet2020.FederalOffice')),
            ],
            bases=('cheatsheet2020.candidate',),
        ),
    ]
