# Generated by Django 3.0.7 on 2020-07-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheatsheet2020', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
